export const LOAD_PHOTO_FROM_API_BEGIN = 'LOAD_PHOTO_FROM_API_BEGIN';
export const LOAD_PHOTO_FROM_API_SUCCESS = 'LOAD_PHOTO_FROM_API_SUCCESS';
export const LOAD_PHOTO_FROM_API_FAILURE = 'LOAD_PHOTO_FROM_API_FAILURE';
export const UPDATE_START_DATE = 'UPDATE_START_DATE';
export const UPDATE_END_DATE = 'UPDATE_END_DATE';
